[package]
name = "poem_api"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = "3.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
futures = "0.3.28"
mongodb = "3.2.3"